### PR TITLE
Fix memory leak in #161 and regression in #194

### PR DESCRIPTION
**Pull request by okmyself**

### CODE REVIEW

**Comment by davdroman** [comment]
Please rebase your branch with the latest master as there are merge conflicts in this PR. Thanks!

**Comment by davdroman** [comment]
@okmyself CI is failing with `UIKitIntrospectionView.swift:80:17: error: invalid redeclaration of 'updateUIView(_:context:)'`.

File: Introspect/UIKitIntrospectionViewController.swift [hunk 1]
```diff
@@ -52,9 +52,16 @@ public struct UIKitIntrospectionViewController<TargetViewControllerType: UIViewC
         return viewController
     }
     
+    /// If you find that the `moveToWindowHandler` is not called in certain situations (which has not been discovered yet),
+    /// you can add code to call the `moveToWindowHandler` in the function body.
```
Comment (davdroman) [inline Introspect/UIKitIntrospectionViewController.swift:56]: This has come to pass as reported in #194 so I'll be taking over and including the fix here.
